name: CI/CD for API Automation

on:
  push:
    branches:
      - main  # Thay thế bằng tên nhánh chính của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Chọn phiên bản Python bạn muốn sử dụng

    - name: Install dependencies
      run: pip install -r requirements.txt  # Cài đặt các dependencies cần thiết

    - name: Run API automation
      run: python reportapiautomation.py  # Thay thế bằng lệnh chạy mã của bạn

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: api-test-report  # Tên báo cáo
        path: api_test_report.pdf  # Tên file PDF bạn đã tạo
